{"uuid": "1b2524fa-9993-4f90-9209-29e180f4cd71", "children": ["50ac666d-c872-42a2-91b9-95aa81d7bef9"], "befores": [{"name": "open_app_without_login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\\\Sdk\\\\platform-tools\\\\adb.exe -P 5037 -s R5CW517VZ9F shell cmd package list packages' exited with code 255'; Command output: \r\nException occurred while executing 'list':\r\njava.lang.SecurityException: Shell does not have permission to access user 150\r\n com.android.server.am.ActivityManagerService.handleIncomingUser:16014 android.app.ActivityManager.handleIncomingUser:5174 com.android.server.pm.PackageManagerShellCommand.translateUserId:3745 \r\n\tat com.android.server.am.UserController.handleIncomingUser(UserController.java:2895)\r\n\tat com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:16014)\r\n\tat android.app.ActivityManager.handleIncomingUser(ActivityManager.java:5174)\r\n\tat com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3745)\r\n\tat com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:1079)\r\n\tat com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:965)\r\n\tat com.android.server.pm.PackageManagerShellCommand.runList(PackageManagerShellCommand.java:805)\r\n\tat com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:242)\r\n\tat com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)\r\n\tat android.os.ShellCommand.exec(ShellCommand.java:38)\r\n\tat com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7259)\r\n\tat android.os.Binder.shellCommand(Binder.java:1104)\r\n\tat android.os.Binder.onTransact(Binder.java:914)\r\n\tat android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4905)\r\n\tat com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7243)\r\n\tat android.os.Binder.execTransactInternal(Binder.java:1380)\r\n\tat android.os.Binder.execTransact(Binder.java:1311)\r\n\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\\\Sdk\\\\platform-tools\\\\adb.exe -P 5037 -s R5CW517VZ9F shell cmd package list packages' exited with code 255'; Command output: \r\nException occurred while executing 'list':\r\njava.lang.SecurityException: Shell does not have permission to access user 150\r\n com.android.server.am.ActivityManagerService.handleIncomingUser:16014 android.app.ActivityManager.handleIncomingUser:5174 com.android.server.pm.PackageManagerShellCommand.translateUserId:3745 \r\n\tat com.android.server.am.UserController.handleIncomingUser(UserController.java:2895)\r\n\tat com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:16014)\r\n\tat android.app.ActivityManager.handleIncomingUser(ActivityManager.java:5174)\r\n\tat com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3745)\r\n\tat com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:1079)\r\n\tat com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:965)\r\n\tat com.android.server.pm.PackageManagerShellCommand.runList(PackageManagerShellCommand.java:805)\r\n\tat com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:242)\r\n\tat com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)\r\n\tat android.os.ShellCommand.exec(ShellCommand.java:38)\r\n\tat com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7259)\r\n\tat android.os.Binder.shellCommand(Binder.java:1104)\r\n\tat android.os.Binder.onTransact(Binder.java:914)\r\n\tat android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4905)\r\n\tat com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7243)\r\n\tat android.os.Binder.execTransactInternal(Binder.java:1380)\r\n\tat android.os.Binder.execTransact(Binder.java:1311)\r\n\n    at getResponseForW3CError (C:\\Users\\a.jamshidi\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\errors.js:1145:9)\n    at asyncHandler (C:\\Users\\a.jamshidi\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\protocol.js:485:57)\n", "trace": "  File \"C:\\Users\\a.jamshidi\\android_automation\\android_automation\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\a.jamshidi\\android_automation\\android_automation\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"C:\\Users\\a.jamshidi\\android_automation\\android_automation\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\a.jamshidi\\android_automation\\android_automation\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\a.jamshidi\\android_automation\\android_automation\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"G:\\android_automation\\conftest.py\", line 59, in open_app_without_login\n    driver = webdriver.Remote(appium_url, options=options)\n  File \"C:\\Users\\a.jamshidi\\android_automation\\android_automation\\.venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 229, in __init__\n    super().__init__(\n  File \"C:\\Users\\a.jamshidi\\android_automation\\android_automation\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\a.jamshidi\\android_automation\\android_automation\\.venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 319, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"C:\\Users\\a.jamshidi\\android_automation\\android_automation\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\a.jamshidi\\android_automation\\android_automation\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1729493185307, "stop": 1729493192281}], "start": 1729493185307, "stop": 1729493192381}