WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000285BAD1AA00>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
INFO     conftest:conftest.py:62 App opened without logging in.
INFO     utils.config:test_create_account.py:47 Clicked on 'Allow' button for notification permission.
INFO     utils.config:test_create_account.py:52 کلیک روی دکمه 'ایجاد حساب کاربری'...
INFO     utils.config:test_create_account.py:59 No nCreate Account button displayed, continuing.
INFO     utils.config:test_create_account.py:65 Clicked on 'Allow' button for notification permission.
INFO     utils.config:test_create_account.py:71 کلیک روی دکمه 'باز کردن حساب'...
INFO     utils.config:test_create_account.py:74 دکمه 'باز کردن حساب' کلیک شد.
INFO     utils.config:test_create_account.py:78 انتخاب سرور 'UAT'...
INFO     utils.config:test_create_account.py:81 سرور 'UAT' انتخاب شد.
INFO     utils.config:test_create_account.py:90 متن تایتل برای صفحه توضیحات صحیح است: در فرایند بازکردن حساب در بلو به موارد زیر نیاز خواهید داشت:
ERROR    utils.config:test_create_account.py:106 خطا در بررسی متن ساعت صفحه توضیحات: Expected '۷ دقیقه زمان!', but got 'در فرایند بازکردن حساب در بلو به موارد زیر نیاز خواهید داشت:'
assert 'در فرایند با... خواهید داشت:' == '۷ دقیقه زمان!'
  
  - ۷ دقیقه زمان!
  + در فرایند بازکردن حساب در بلو به موارد زیر نیاز خواهید داشت:
INFO     utils.config:test_create_account.py:113 کلیک روی دکمه 'شروع'...
INFO     utils.config:test_create_account.py:116 دکمه 'شروع' کلیک شد.
INFO     utils.config:test_create_account.py:121 Initial switch status: OFF
INFO     utils.config:test_create_account.py:124 Switch status after toggle: ON
INFO     utils.config:test_create_account.py:128 کلیک روی دکمه 'تایید'...
INFO     utils.config:test_create_account.py:130 دکمه 'تایید' کلیک شد و به صفحه وارد کردن شماره تلفن هدایت شد.
INFO     utils.config:test_create_account.py:137 شماره تلفن وارد شد: 09122367181
INFO     utils.config:test_create_account.py:142 دکمه 'بعدی' کلیک شد.
INFO     utils.config:test_create_account.py:150 متن ریفرال صحیح است: مانند:‌ MDMGKP
INFO     utils.config:test_create_account.py:154 دکمه 'بعدی' کلیک شد.
INFO     utils.config:test_create_account.py:162 متن کد ملی صحیح است: کد ملی ۱۰ رقمی
INFO     utils.config:test_create_account.py:167 کدملی وارد شد: 7187488246
INFO     utils.config:test_create_account.py:171 دکمه 'بعدی' کلیک شد.
INFO     utils.config:test_create_account.py:177 سال با موفقیت اسکرول شد.
INFO     utils.config:test_create_account.py:181 دکمه 'بعدی' کلیک شد.
ERROR    utils.config:test_create_account.py:295 خطا رخ داد: Message: 
Stacktrace:
NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.findElOrEls (C:\Users\a.jamshidi\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\find.ts:86:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\Users\a.jamshidi\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:60:12)
    at AndroidUiautomator2Driver.findElement (C:\Users\a.jamshidi\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:75:12)